### ISSUE TITLE
Crash / stuck when entering a new world with zombie_variants 1.21.1

### ISSUE THREAD

**Issue by chmonyasik** [DeusSixik/Tpsum#3]
Minecraft 1.21.1
NeoForge 21.1.216

zombie_variants-neoforge-1.0.3-1.21.1
tpsum-1.21.1-0.0.3

Java 25 Adoptium
`-XX:+UnlockExperimentalVMOptions  -XX:+UseZGC  -XX:+ZGenerational -XX:+DisableExplicitGC  -XX:+AlwaysPreTouch  -XX:+PerfDisableSharedMem -XX:+ParallelRefProcEnabled  -XX:+UnlockDiagnosticVMOptions  -XX:+OptimizeStringConcat  -XX:+UseCriticalJavaThreadPriority  -Djava.locale.providers=JRE  --enable-native-access=ALL-UNNAMED`

https://mclo.gs/Ad5aCPk

**Comment by DeusSixik** [comment]
Fixed on commit dcc0767

It should be available on CurseForge soon.

**Comment by chmonyasik** [comment]
https://mclo.gs/B85ojAL
tpsum-1.21.1-0.0.5

still happening, as far as I understand

**Comment by DeusSixik** [comment]
Must be fixed on 7d1d929 commit

It should be available on CurseForge soon.
